# docker-compose.yml
version: '2'
services:
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
    node-exporter-1:
        image: prom/node-exporter
        ports:
            - '9100:9100'
    node-exporter-2:
        image: prom/node-exporter
        ports:
            - '9200:9100'
    node-exporter-3:
        image: prom/node-exporter
        ports:
            - '9300:9100'
    grafana:
        image: grafana/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=pass
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
volumes:
        prometheus_data: {}
        grafana_data: {}
