# prometheus.yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
       - targets: ['localhost:9090']
    - job_name: 'node-exporter-1'
      static_configs:
       - targets: ['node-exporter-1:9100']
    - job_name: 'node-exporter-2'
      static_configs:
       - targets: ['node-exporter-2:9100']
    - job_name: 'node-exporter-3'
      static_configs:
       - targets: ['node-exporter-3:9100']
